version: "3"
services:
  myboost:
    container_name: myboost
    image: myboost:1.0
    env_file: .env
    build:
      context: .
      dockerfile: Dockerfile
      args:
        workdir: /home/work
    restart: always
    tty: true
    ports:
      - "8888:8888"
    volumes:
      - .:/home/work
